import graphviz
from graphviz import Digraph
dot = Digraph(format='png')
dot.attr(size="9,9")
# dot.attr(bgcolor = "#fffdd0")
dot.node('A','Thing')
dot.node('B','Staff')
dot.node('C','MedicalStaff')
dot.node('D','Experienced')
dot.node('E','AdminStaff')
dot.node('F','Vehicle')
dot.node('G','Doctor')
dot.node('H','Nurse')
dot.node('I','TransportStaff')
dot.node('J','EmergencyDriver')
dot.node('K','HRDStaff')
dot.node('L','Ambulance')
dot.node('M','Wheeler')
dot.node('N','Wheeler3')
dot.node('O','Wheeler4')
dot.node('P','SeniorDoctor')
dot.node('Q','AsstDoctor')
dot.node('R','SatffNurse')
dot.node('S','GraduateNurse')
dot.node('T','ExpSeniorDoctor')
dot.node('U','AsstDoctorwExpSenior')
dot.node('V','ExpStaffNurse')
dot.node('W','GradNursewExpSenior')
dot.edges(['AB','AF','BC','BE','BD','CG','CH','FL','FM','MN','MO','EI','EK','IJ','DJ','DT','DV','GP','GQ','HR','HS','PT','QU','RV','SW'])
print(dot.source)
dot.render("Taxonomy", view=True)